branch-defaults:
  aws-beanstalk-with-dynamodb:
    environment: production
  default:
    environment: null
    group_suffix: null
  master:
    environment: air-talk-rails
    group_suffix: null
global:
  application_name: air-talk-rails
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.3 (Puma)
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
